### ISSUE TITLE
[Bug]: Negative Size during Bundle Decompression

### ISSUE THREAD

**Issue by raimomo** [AssetRipper/AssetRipper#1143]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

Girl Cafe Gun (the game is dead, can provide .obb file if needed)

### Which Unity version did this occur on?

2018.4.36f1

### Is the game Mono or IL2Cpp?

Unknown

### Describe the issue.

On folder open process throw the error "System.OverflowException: Arithmetic operation resulted in an overflow."

### Relevant log output

[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/13765290/AssetRipper.log)

**Comment by ds5678** [comment]
Can you retry this on the latest alpha build? I just pushed a commit related to your issue.

**Comment by raimomo** [comment]
What is considered an alpha build?

**Comment by raimomo** [comment]
Nvm, I have found it. Still getting an error.
[AssetRipper.log](https://github.com/AssetRipper/AssetRipper/files/13767116/AssetRipper.log)

**Comment by ds5678** [comment]
It's possible this is a parsing error. I welcome you to investigate.

**Comment by ds5678** [comment]
Closing this because of inactivity and skepticism about validity. If you find stronger evidence that this is an AssetRipper bug, feel free to reopen the issue.
