### ISSUE TITLE
[Bug]: Crash upon clicking "Open File" or "Open Folder"

### ISSUE THREAD

**Issue by BalancedLight** [AssetRipper/AssetRipper#1595]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

Windows x64

### Which game did this occur on?

N/A

### Which Unity version did this occur on?

N/A

### Is the game Mono or IL2Cpp?

Unknown

### Describe the issue.

This has been happening for a few versions now, and I'm not sure why. I previously bought the premium version of assetripper (1.0.18) and now every free build ive run after just immediately crashes upon opening the windows explorer to open a file or folder.

### Relevant log output

[AssetRipper.log](https://github.com/user-attachments/files/18138984/AssetRipper.log)

[Video](https://github.com/user-attachments/assets/6076488f-34de-4aed-8cd4-b54ab98fcfce)

**Comment by ds5678** [comment]
I had one other user mention this. For them, the problem started when I switched to .NET 9 in the 1.1.5 release. Their OS was Windows 11. Does this align with your experience?

You seemed to imply that these crashes only happen with the free edition. Is it correct that the premium edition is functioning fine?

**Comment by wintbiit** [comment]
Also running into this.
AssetRipper v1.1.8
Windows 11 24H2 version 26100.2605

**Comment by wintbiit** [comment]
> Also running into this. AssetRipper v1.1.8 Windows 11 24H2 version 26100.2605

PS: Switching to AssetRipper v1.1.4 would work.

**Comment by BalancedLight** [comment]
> I had one other user mention this. For them, the problem started when I switched to .NET 9 in the 1.1.5 release. Their OS was Windows 11. Does this align with your experience?
> 
> You seemed to imply that these crashes only happen with the free edition. Is it correct that the premium edition is functioning fine?

Yes, running 1.1.4, there are no issues and i can open folders and files as needed, anything after will crash upon opening a folder.  I am also using Windows 11. 

I didn't have .NET 9 runtimes installed, but I installed them and the program still crashes on the most recent versions.

**Comment by ds5678** [comment]
For clarity, AssetRipper does not depend on a local installation of .NET.

In any case, this seems like a bug in the runtime. I'm looking to see if anyone else reported this to the .NET team.

**Comment by ds5678** [comment]
@BalancedLight Can you try the commit I just pushed? A new patch version of .NET 9 came out recently, and I want to see if that had any impact.

**Comment by BalancedLight** [comment]
I downloaded and built the most recent version of the code and it still crashed, but this time I was able the get the error 
`The program '[28612] AssetRipper.GUI.Free.exe' has exited with code 3221226505 (0xc0000409).`
from the debugger

**Comment by ds5678** [comment]
> and built

This is not the same as downloading a continuous integration build.

**Comment by BalancedLight** [comment]
I'm sorry, I don't understand what that is or where to find that.

**Comment by ds5678** [comment]
https://github.com/AssetRipper/AssetRipper/actions/workflows/publish.yml

**Comment by wintbiit** [comment]
I tried latest action artifact from https://github.com/AssetRipper/AssetRipper/actions/runs/12461850745. Still crashes after clicking "Open File" / "Open Folder"

**Comment by wintbiit** [comment]
> I tried latest action artifact from https://github.com/AssetRipper/AssetRipper/actions/runs/12461850745. Still crashes after clicking "Open File" / "Open Folder"

Is it possible that "select file/folder" be handled by frontend instead of .NET? I think this would provider better compatibility.

**Comment by ds5678** [comment]
> Is it possible that "select file/folder" be handled by frontend instead of .NET? I think this would provider better compatibility.

No, at least not with the browser. It has protections against leaking file paths to websites.

**Comment by Greenball233** [comment]
Met the same bug when using the free version of 1.1.13
Windows 11 24H2

**Comment by Greenball233** [comment]
By the way, I tracked the code where Asset Ripper used for showing File Select Dialog and found Nfd.PickFolderMultiple(), but when I tried to use it directly in my newly-created project using .NET 8.0, it works.
