### ISSUE TITLE
Bad PPtr in Sprite Export

### ISSUE THREAD

**Issue by Danl54** [AssetRipper/AssetRipper#556]
### Are you on the latest version of AssetRipper?

Yes, I'm on the latest release of AssetRipper.

### Which release are you using?

GUI Version Windows x64

### Which game did this occur on?

Critical Ops:
https://play.google.com/store/apps/details?id=com.criticalforceentertainment.criticalops

### Which Unity version did this occur on?

Unity 2021.3.9

### Is the game Mono or IL2Cpp?

IL2Cpp

### Describe the issue.

Asset Ripper just doesn't open the game(Critical Ops). Could You please fix it. I gave you the log down here.
Have a nice day! Wish everything is good.

### Relevant log output

[AssetRipper.log.txt](https://github.com/AssetRipper/AssetRipper/files/9645670/AssetRipper.log.txt)

**Comment by ds5678** [comment]
I just pushed a new version of AssetRipper. Can you try on that version?

**Comment by Danl54** [comment]
Okay let me test it. Изпратено от Поща за Windows От: ds5678Изпратено: 28 септември 2022 г. 21:50До: AssetRipper/AssetRipperЯк: Dani54; AuthorТема: Re: [AssetRipper/AssetRipper] AssetRipper doesn't open(import) Critical Ops. And im not able to export the scenes. (Issue #556) I just pushed a new version of AssetRipper. Can you try on that version?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by Danl54** [comment]
Nah still not working Изпратено от Поща за Windows От: ds5678Изпратено: 28 септември 2022 г. 21:50До: AssetRipper/AssetRipperЯк: Dani54; AuthorТема: Re: [AssetRipper/AssetRipper] AssetRipper doesn't open(import) Critical Ops. And im not able to export the scenes. (Issue #556) I just pushed a new version of AssetRipper. Can you try on that version?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by ds5678** [comment]
Try https://github.com/AssetRipper/AssetRipper/actions/runs/3588783128 and let me know how it goes.
